# Generated by Django 4.2.25 on 2025-10-22 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='places/gallery/', verbose_name='Фотография')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись к фото')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mainapp.places', verbose_name='Локация')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'Фотографии',
            },
        ),
    ]
