# Generated by Django 4.2.25 on 2025-10-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_placeimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='caption',
        ),
    ]
