# Generated by Django 4.2.25 on 2025-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_placeimage_caption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['order'], 'verbose_name': 'фотография', 'verbose_name_plural': 'Фотографии'},
        ),
        migrations.AddField(
            model_name='placeimage',
            name='caption',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подпись к фото'),
        ),
        migrations.AddField(
            model_name='placeimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
