# Generated by Django 4.2.25 on 2025-10-23 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_placeimage_order_alter_places_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='places',
            name='slug',
        ),
    ]
